### PR TITLE
Added first README and changed _generate.sh

### PR DESCRIPTION
**Pull request by smlmbrt**
The old version didn't seem to generate the random sequences automatically, I changed the README to have a step where random sequences are made.

### CODE REVIEW

**Comment by hsnajafabadi** [comment]
The sequences actually need to be exactly the same as what we've been working with, otherwise database comparison would not work (we have precomputed the database affinities using a particular set of random sequences). I'm going to remove _generate.sh, and put the random sequences instead.

**Comment by smlmbrt** [comment]
Is it possible to set the random seed in the script? That would make it consistent, and then the software will be 40 mb smaller. 

And for anyone who downloads it they'll only have to do it once, so it won't be random every time.

**Comment by hsnajafabadi** [comment]
The problem is, each awk version has a different random number generator, and even with the same seed number, the results could be different. The results would be much more stable if we just put the sequences there.

**Comment by smlmbrt** [comment]
Sounds good, I'll make those changes.

**Pull request closed without merging**
